### ISSUE TITLE
No valid secondary alignment found in bam file

### ISSUE THREAD

**Issue by jhwan1203** [a-slide/NanoCount#10]
Hi,

following your step "mininap2 -ax map-ont -p 0 -N 10 " before alignment.
but, I have an error "No valid secondary alignment found in bam file".

I really don't know how to solve this error.

Someone who solved this error, please tell me how to solve it.

Thank you

**Comment by a-slide** [comment]
Guess it is just because there aren’t any secondary alignment in your bam file. In that case just count the number of reads per transcripts
