### ISSUE TITLE
Setting -3 to -1 to deactivate fails

### ISSUE THREAD

**Issue by josiegleeson** [a-slide/NanoCount#11]
Hello, two comments.

When setting the -3 setting to -1 to deactivate, it throws an error:
NanoCount: error: argument -3/--max_dist_3_prime: expected one argument
I have been able to deactivate it by just setting the cutoff to a very high number instead.

Also there is a typo in the argument: discard_suplementary
As it should be: discard_supplementary

Thank you!

**Comment by a-slide** [comment]
Hi Josie,

Thanks for reporting the bugs.
I will take care of those as soon as I can.

**Comment by a-slide** [comment]
fix in 1.0
