### ISSUE TITLE
Adding option for cDNA reads

### ISSUE THREAD

**Issue by camillaugolini-iit** [a-slide/NanoCount#12]
Hi,

it should be useful to have an option to disable filtering on reverse flag in order to process also cDNA reads.

Many thanks

**Comment by BaylorLyu** [comment]
and it's also useful to have an option to metagenome.
Many thanks

**Comment by a-slide** [comment]
I am aware of this. I am a little reluctant to do it without a proper evaluation of the reliability on cDNA data.
In the paper we evaluated on dRNA data only.

**Comment by josiegleeson** [comment]
The latest release (1.1.0) now has the option to disable removing the negative strand reads. Please note, this hasn't been benchmarked on cDNA but the option is now there. The flag is -n.
