### ISSUE TITLE
Minimum number of ONT reads per sample

### ISSUE THREAD

**Issue by ms-gx** [a-slide/NanoCount#13]
I would like to do a an analysis using NanoCount on human cell lines. We do not have to capture super rare transcripts.

The experimental setup is:
2 Conditions x 3 biological replicates

I was thinking about generating about 10 Mio. ONT reads per biological sample. So total number of reads would be 60 Mio in total for all 6 biol. samples.

What would be the minimum number of reads you suggest to target per biological sample? I know this is highly dependent on the type of analysis. I am just interested in a rough estimate.

**Comment by josiegleeson** [comment]
Hello, apologies for the late reply. 10 million reads per sample will be sufficient, in the Gleeson et al. paper we had much less than this. For more information on replicates required see this paper: https://rnajournal.cshlp.org/content/22/6/839.long.
