### ISSUE TITLE
Different options when using minimap

### ISSUE THREAD

**Issue by Tomcxf** [a-slide/NanoCount#14]
I used to do the following command to map my direct RNA data by nanopore.
`minimap2 -ax map-ont -splice -uf -k14 the_reference_transcriptome.fa basecall_by_guppy.fastq > minimap_transcriptome.sam`
And when I tried the command you recommend 
`minimap2 -t 4 -ax map-ont -p 0 -N 10 transcriptome.fa.gz reads.fastq.gz`
I got a larger file. Both the bam file and count file created by nanocount.
I noticed you said the -N is about the secondary mapping. But when I used samtools flagstat, I found both of them have no secondary mapping. And the recommend command make more mapping.
So I don't know what cause that. Should I use the recommend command to do the analysis instead of the formed command?
Because the former command is recommened by Minimap offically.
Thank you!

**Comment by Tomcxf** [comment]
oh 
I found the secondary you recommended is larger than former.
It also cause larger mapping rate.
Is that the control is less strict? Will it effect the consequence?

**Comment by josiegleeson** [comment]
Hello, apologies for the delayed response.

Running minimap2 with the -N 10 flag should retain up to 10 secondary alignments. You can use this command or just the default minimap2 command 'minimap2 -ax map-ont transcriptome.fa reads.fastq' and this should work fine as well if you're having issues. 

There is no need to include the -splice flag when you map to the transcriptome. Only use this for the genome mapping. 

Let me know if you need more help.
Josie.
