### ISSUE TITLE
nanocount for two condition 

### ISSUE THREAD

**Issue by rezarahman12** [a-slide/NanoCount#15]
Hi Gleeson and team,
Thank you for developing beautiful and easy-to-use NanoCount program for estimating transcript abundance from dRNA-Seq data.

I have successfully run the nanocount and obtained the output tsv file. I ran one for condition A and then ran on condition B, so I have two output files. In order to perform differential expression analyses using DESeq2, I need to have a single data matrix that will have transcripts and nanocount output for condition A and condition B together.

I will appreciate it if you kindly advise how to combine or merge the two output tsv file in order to perform differential analysis.

Thank you so much.
Kind regards
Reza

**Comment by josiegleeson** [comment]
Hi Reza,

You'll need to import your tables into R and merge them based on the 'transcript_name' column. The 'est_count' column are the counts you should use for DESeq2. You can rename this column first to your sample name. You'll also need to round the counts to integers for DESeq2, using the round() function in R.

Please see:
https://www.statmethods.net/management/merging.html

Hope that helps!

**Comment by rezarahman12** [comment]
Hi Josie,
Thank you for your prompt reply. Thank you so much.
Best regards
Reza

**Comment by vetmohit89** [comment]
Hello Josie,

I have used transcriptome reference file for mapping. I want to aggregate transcript abundances to the gene level? How can I do it? Some of the transcripts are smaller in size not sure if they have any relevance in gene expression?

Thank you
Mohit

**Comment by josiegleeson** [comment]
Hi Mohit,

You can use tximport for this, specifically the summarizeToGene function.

Check out their documentation here: https://bioconductor.org/packages/devel/bioc/vignettes/tximport/inst/doc/tximport.html

Thanks

**Comment by vetmohit89** [comment]
Hello Josie,

Thank you so much for reply. I am wondering  what quantification tool name should I use at "TYPE" as the tximport pipeline will be nearly identical for various quantification tools, usually only requiring one change the type argument. It seems that it will recognise only Salmon, Alevin, Sailfish, kallisto,RSEM, StringTie. What should I keep at "type" for running tximport.

**Comment by vetmohit89** [comment]
Hello Josie,

I am having difficulty in converting transcript to gene level data. Getting errors so I posted on biostars. Would you mind if you please help me with this issue?

https://www.biostars.org/p/9569629/

Thank you
Mohit

**Comment by Bathroomboss** [comment]
> Hi Josie, Thank you for your prompt reply. Thank you so much. Best regards Reza

Hi Reza,
Since you have two output files, one for condition A and one for condition B, and you lack replicates. How do you perform DESeq2 analysis?
Best
Yu
