### ISSUE TITLE
nanocount fast5 files

### ISSUE THREAD

**Issue by rezarahman12** [a-slide/NanoCount#17]
Hi Josie,
I have downloaded fast5 files of undiff1 sample (undiff1.tar.gz) of the nanocount paper from the ENA database. When I untar the undiff.tar.gz file it created a folder "2018.04.12_SHSY5Y_Undiff3_dirRNA". Inside that folder, I saw six different folders, each of which contain a fast5 folder. I have attached screenshots of the folder. Should I need to consider all the fast5 files of those six folders for analysis?
Thanks 
Best regards
Reza
[nanocount_fast5files.docx](https://github.com/a-slide/NanoCount/files/9769409/nanocount_fast5files.docx)

**Comment by josiegleeson** [comment]
Yes those files inside should all be used. The difference in names from undiff1 to undiff3 is because we originally had more/different samples. But the undiff3 directory inside the tar will correspond to undiff1.
