### ISSUE TITLE
alignmnet using sequin reference

### ISSUE THREAD

**Issue by rezarahman12** [a-slide/NanoCount#18]
Dera NanoCount team,

I noted in the NanoCount paper that the ONT data generated were first aligned to human and sequin genome and transcriptome using minimap2. 

"FASTQ files containing ONT pass reads were aligned to the human (GRCh38) and synthetic sequin genome and transcriptome using minimap2 (v2.17)."

Could you please clarify whether two separate alignmnet steps were done- one for human transcriptome and another for sequin transcriptome? 

Could you please share the script that you have used for alignmnent using minimap2?

I do highly appreciate your time and help.
Kind regards
Reza

**Comment by josiegleeson** [comment]
Hi Reza,

Yes I mapped them separately so I could quantify the transcripts separately. You could also map together and separate the files later, it shouldn't make a difference. 

Here's what I did for each sample:
minimap2 -ax map-ont human_transcripts.fa sample.fastq > human_sample_transcriptomic_aln.sam
minimap2 -ax map-ont sequin_transcripts.fa sample.fastq > sequin_sample_transcriptomic_aln.sam
