### ISSUE TITLE
-N 100 hinder NanoCount accuracy? 

### ISSUE THREAD

**Issue by callumparr** [a-slide/NanoCount#19]
I used the following command from minimap2 

`minimap2 -t 4 -ax map-ont -p 1.0 -N 100 -k14 -uf index/transcriptome_index.mmi`

In the readme, it is recommended to use -N 10. Would having potentially more secondary alignments hinder the NanoCount accuracy? 

Ideally, I would not like to remap all my samples again as just want to see a comparison of salmon vs NanoCount for each sample.

**Comment by josiegleeson** [comment]
Hi, 

I wouldn't worry. NanoCount will filter out any secondary alignments that aren't very good/nearly as good as the primary alignment. So it shouldn't affect your results.

**Comment by callumparr** [comment]
Thank you 🙏
