### ISSUE TITLE
Why NanoCount needs sorted alignments?

### ISSUE THREAD

**Issue by callumparr** [a-slide/NanoCount#20]
Out of interesting question because salmon actually recommends not having alignments sorted, so was wondering why the difference. Both are forms of maximizing expectations so is there ar reason having sorted alignments is better than unsorted?

**Comment by josiegleeson** [comment]
From my understanding, it just speeds up the process to have them sorted. NanoCount will run on unsorted bam files it just takes a little longer. Unsure for salmon though, it might be required for it to run or something to do with short read alignments which it is designed for?

**Comment by callumparr** [comment]
Thank you for the explanation
