### ISSUE TITLE
Too many reads are discarded

### ISSUE THREAD

**Issue by vetmohit89** [a-slide/NanoCount#26]
Hello,

I have followed the 

minimap2 -t 4 -ax map-ont -p 0 -N 10 transcriptome.fa.gz reads.fastq.gz | samtools view -bh > aligned_reads.bam
sorted them and used sorted file for nanocount:

But when I used NanoCount -i reads.sorted.bam -b reads_selected.sorted.bam --extra_tx_info -n -o test-3.tx_counts.tsv
Discarded alignment with invalid 3 prime end: 816,353

I can see reads are present in bam file but it is removed during nanocount processing. 

**Here is the whole process:**

Parse Bam file and filter low quality alignments
        Summary of alignments parsed in input bam file
                Valid alignments: 1,930,498
                Discarded alignment with invalid 3 prime end: 816,353
                Discarded unmapped alignments: 36,322
                Discarded supplementary alignments: 18,593
                Discarded short alignments: 53
        Summary of reads filtered
                Invalid secondary alignments: 737,516
                Valid secondary alignments: 629,220
                Reads with valid best alignment: 545,953
                Reads with low query fraction aligned: 7,056
        Write selected alignments to BAM file
        Summary of alignments written to bam
                Alignments skipped: 1,626,646
                Alignments to select: 1,175,173
                Alignments written: 1,175,173
        Generate initial read/transcript compatibility index
## Start EM abundance estimate ##
        Progress: 13.0 rounds [00:17, 1.36s/ rounds]
        Exit EM loop after 13 rounds
        Convergence value: 0.004977198951329835

Can you help me figure out how not to loose so many reads? It changes the whole output if we loose so many reads. 

Thank you
Mohit

**Comment by josiegleeson** [comment]
Hi Mohit,

So 'reads' and 'alignments' here are different things. When NanoCount discards the 816,353 alignments, these are likely secondary alignments and therefore the read itself is kept with hopefully only one or two alignments of high quality remaining. The number of reads in the filtered bam file will hopefully not be much less than you started with. 

Try checking this which will give you the number of unique read IDs in the file:
samtools view aligned_reads.bam | awk '{print $1}' | sort | uniq | wc -l 

Josie.
