### ISSUE TITLE
Nanocount vs Flair

### ISSUE THREAD

**Issue by sagnikbanerjee15** [a-slide/NanoCount#28]
Hello,

I am using Nanocount to estimate expression levels. I found that Flair quantifies the transcripts after finding novel ones. Is it sufficient to accept the results of Flair quantify or is it necessary to execute Nanocount?

Thank you

**Comment by josiegleeson** [comment]
Hi,

It's up to you really, but we benchmarked NanoCount with FLAIR and found that NanoCount performed better and removed some false positive novel transcripts. So I would recommend parsing the output from FLAIR into NanoCount for quantification.

Hope this helps.

**Comment by sagnikbanerjee15** [comment]
Hello,

Thanks for the reply. I was comparing the counts from FLAIR with Nanocounts and I found that several transcripts had a difference of over 500 counts. Could there be any reason for that difference?

Thank you.

**Comment by josiegleeson** [comment]
Hi, FLAIR may have found novel isoforms that have incorrect 3' ends, and NanoCount can then remove these incorrect isoforms (by assigning them 0 counts). They also likely use different quantification algorithms so both of these are likely causing the differences. Thanks.
