### ISSUE TITLE
TPM values do not sum up to 1 million

### ISSUE THREAD

**Issue by lpryszcz** [a-slide/NanoCount#3]
Hi, when I ran nanoCompare on my data (dRNAseq mapped with minimap2) I obtained weird TPM values that sum to `5.86092000e+11 6.12210923e+12 3.26647657e+12 1.93848398e+09` instead of 1e6. When I TPM normalise them later on everything seems fine. Any idea?

NanoCount TPM values
![nanocount scatter](https://user-images.githubusercontent.com/988152/64327713-7386c180-cfcc-11e9-94ef-2b0cd7e94cab.png)

NanoCount TPM values TPM normalised
![nanocount scatter tmp_norm](https://user-images.githubusercontent.com/988152/64327763-88635500-cfcc-11e9-95ae-8881b4e96422.png)

NanoCount est_count values TPM normalised
![nanocount scatter est_count_norm](https://user-images.githubusercontent.com/988152/64327800-974a0780-cfcc-11e9-82c1-8c6cefa714bb.png)

NanoCount raw values TPM normalised
![nanocount scatter raw_norm](https://user-images.githubusercontent.com/988152/64327844-acbf3180-cfcc-11e9-88cc-e3eea07c630c.png)

**Comment by a-slide** [comment]
Hi @lpryszcz and @tleonardi,
I realise that it took me a bit of time to do it, but this is now fixed :s  together with a bunch of other problems and optimizations.
I will close the issue, but please reopen if you think otherwise
Cheers
