### ISSUE TITLE
High % of reads lost due to discarded negative strand and invalid 3' end.

### ISSUE THREAD

**Issue by NStrowbridge** [a-slide/NanoCount#30]
Josie,

I raised a similar issue before. Sorry, I haven't got back to you as I was busy with other work and forgot to check this. I've actually got more samples and have been trying to conduct Nanocount again. I am still getting quite a few discarded alignments. Both for negative strand alignments and invalid 3' end alignments. I.e

1;34m## Initialise Nanocount ##�[0m
�[32m Parse Bam file and filter low quality alignments�[0m
�[32m Summary of alignments parsed in input bam file�[0m
�[32m Discarded negative strand alignments: 1,461,447�[0m
�[32m Discarded alignment with invalid 3 prime end: 1,197,522�[0m
�[32m Valid alignments: 402,524�[0m
�[32m Discarded unmapped alignments: 56,911�[0m
�[32m Discarded supplementary alignments: 7,345�[0m
�[32m Summary of reads filtered�[0m
�[32m Reads with valid best alignment: 202,817�[0m
�[32m Valid secondary alignments: 125,693�[0m
�[32m Invalid secondary alignments: 69,228�[0m
�[32m Reads with low query fraction aligned: 3,466�[0m
�[32m Write selected alignments to BAM file�[0m
�[32m Summary of alignments written to bam�[0m
�[32m Alignments skipped: 2,797,239�[0m
�[32m Alignments to select: 328,510�[0m
�[32m Alignments written: 328,510�[0m
�[32m Generate initial read/transcript compatibility index�[0m

I've checked the read numbers before and after NanoCount and I am only getting ~1/3 of the reads used as input due to discarding. Do you have any idea why this might be happening?

**Comment by josiegleeson** [comment]
Hi again,

Hmm this does seem odd. Typically direct RNA sequencing produces reads on the positive strand, so I am not sure why so many would be mapping to the negative strand. Are you sure this is direct RNA and not cDNA of some kind?

And are you definitely checking the number of reads before and after, not just number of alignments? These will be quite different and it is expected that the number of alignments will be much smaller after. 

Would you be comfortable sharing one of the BAM files with me if this doesn't solve the issue?

Thank you

**Comment by KunFang93** [comment]
Hi,

I opened another question but I found I might have the same problem.

I have a bam file with flagstat:
```
samtools flagstat -@ 30 ../minimap2/gHoxB13_trim_filt1k.1006.bam
50123897 + 0 in total (QC-passed reads + QC-failed reads)
5400516 + 0 primary
42253524 + 0 secondary
2469857 + 0 supplementary
0 + 0 duplicates
0 + 0 primary duplicates
49948193 + 0 mapped (99.65% : N/A)
5224812 + 0 primary mapped (96.75% : N/A)
0 + 0 paired in sequencing
0 + 0 read1
0 + 0 read2
0 + 0 properly paired (N/A : N/A)
0 + 0 with itself and mate mapped
0 + 0 singletons (N/A : N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)
```
And the command I used:
```
NanoCount -i ../minimap2/gHoxB13_trim_filt1k.1006.bam -b gHoxB13_trim_filt1k_selected.1006.bam --extra_tx_info -o gHoxB13_counts.1006.tsv
```
The output from screen
```
## Checking options and input files ##
## Initialise Nanocount ##
	Parse Bam file and filter low quality alignments
[E::idx_find_and_load] Could not retrieve index file for '../minimap2/gHoxB13_trim_filt1k.1006.bam'
^@^@	Summary of alignments parsed in input bam file
		Discarded negative strand alignments: 31,402,884
		Discarded alignment with invalid 3 prime end: 13,925,303
		Valid alignments: 2,371,904
		Discarded supplementary alignments: 2,247,105
		Discarded unmapped alignments: 175,704
		Discarded short alignments: 997
	Summary of reads filtered
		Valid secondary alignments: 1,300,964
		Reads with valid best alignment: 435,817
		Reads with low query fraction aligned: 237,996
		Invalid secondary alignments: 209,290
	Write selected alignments to BAM file
[E::idx_find_and_load] Could not retrieve index file for '../minimap2/gHoxB13_trim_filt1k.1006.bam'
^@^@^@	Summary of alignments written to bam
		Alignments skipped: 48,387,116
		Alignments to select: 1,736,781
		Alignments written: 1,736,781
	Generate initial read/transcript compatibility index
^@## Start EM abundance estimate ##
	Progress: 16.0 rounds [00:22, 1.42s/ rounds]
	Exit EM loop after 16 rounds
	Convergence value: 0.0049077238083319015
## Summarize data ##
	Convert results to dataframe
	Compute estimated counts and TPM
```
And the selected.bam file's flagstat
```
1736781 + 0 in total (QC-passed reads + QC-failed reads)
275101 + 0 primary
1461680 + 0 secondary
0 + 0 supplementary
0 + 0 duplicates
0 + 0 primary duplicates
1736781 + 0 mapped (100.00% : N/A)
275101 + 0 primary mapped (100.00% : N/A)
0 + 0 paired in sequencing
0 + 0 read1
0 + 0 read2
0 + 0 properly paired (N/A : N/A)
0 + 0 with itself and mate mapped
0 + 0 singletons (N/A : N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)
```

It looks like most of the reads are discarded... I wondered if you have any suggestion for this? Thanks for your time and help!

Best,
Kun

**Comment by josiegleeson** [comment]
Please count the unique read IDs in the original and filtered BAM files as below:
samtools view aligned_reads.bam | awk '{print $1}' | sort | uniq | wc -l
