### ISSUE TITLE
Est_count doesn't match records

### ISSUE THREAD

**Issue by KunFang93** [a-slide/NanoCount#32]
Hi,

Thanks for providing this wonderful tool! I am a fresh user for NanoCount and this might be a silly question..: I have used the command
`NanoCount -i ../minimap2/gControl_trim_filt1k.sam -b gControl_trim_filt1k_selected.bam --extra_tx_info -o gControl_counts.tsv`
to run nanocount.

And I summed all est_count in gControl_counts.tsv file and got the total number of 455586, however, I checked gControl_trim_filt1k.sam and it has 5184460 mapped reads. I wondered why there are such big difference in term of number of reads? 

Thanks in advance!

Best,
Kun

**Comment by KunFang93** [comment]
I double checked with my experiment labmate and found my data is from direct cDNA sequencing... sry for bothering...

**Comment by josiegleeson** [comment]
Hi Kun,

If you have cDNA data you can disable the 3' end filtering by using '-d -1' in the command. However, we haven't benchmarked this extensively.

Thanks,
Josie.

**Comment by KunFang93** [comment]
Sorry for late reply. Yes, I saw it in the manual~ thanks for providing this wonderful tool!
