### ISSUE TITLE
Normalised the reads count

### ISSUE THREAD

**Issue by M-Chi-1** [a-slide/NanoCount#33]
Hi,

I would like to quantify the gene expression in treated and untreated condition. The total reads count is low in my treated condition. So I am wondering would the nanocount take in consideration the difference in the total reads count or do I need to down samples the total reads count in both conditions? Please see the attached
<img width="563" alt="Screenshot 2023-11-20 at 13 54 10" src="https://github.com/a-slide/NanoCount/assets/145863561/996edd17-6fa6-444a-bc18-9fbad6f0bb17">

Thanks in advance

**Comment by josiegleeson** [comment]
Hi, keep in mind NanoCount is for transcript expression not gene expression. However, you can still quantify the transcripts in your samples. The output contains a column called 'tpm' which is normalised (transcripts per million) but if you're hoping to run a differential expression analysis, please use the 'est_count' column for the counts as most differential expression programs do their own normalisation for depth. Hope this helps.
