### ISSUE TITLE
How can I obtain the raw file containing reads assigned to isoforms?

### ISSUE THREAD

**Issue by zhenyu7500** [a-slide/NanoCount#34]
Thank you for creating the excellent NanoCount software.

I am interested in obtaining information about the assignment of DRS reads to isoforms, but I couldn't locate this information in the output files. Do you have any suggestions?

I appreciate your prompt response.

Thank you!

**Comment by josiegleeson** [comment]
Hi, ensure you run NanoCount with the '-b' flag enabled and provide a name for the output BAM file. This will output the BAM file which has all the reads included for quantification and which transcript isoforms they were mapped to. You can convert this to a SAM file to view it. Hope that helps!
