### ISSUE TITLE
How do NanoCount deal with reads with multiple alignments?

### ISSUE THREAD

**Issue by kerenzhou062** [a-slide/NanoCount#36]
Hi Josie,

I would like to know that how do NanoCount deal with reads with multiple alignments? I know the EM algorithm was employed to estimate the transcript abundance, but it's not clear how it handle the multiple alignments. For example, for fragmented RNAs (such as extracellular RNAs) of which only part of them were preserved and may be mapped to multiple transcripts.

Looking forward to hearing from you!

Best,

Keren

**Comment by josiegleeson** [comment]
Hi Keren, apologies for the late reply!

Yes multiple alignments (primary and many secondary) will all be kept with NanoCount, pending they all have a good alignment score (compared to the primary/best alignment). Then the EM algorithm will weight the alignments during quantification so the read will effectively be split among these alignments. Keep in mind that usually with direct RNA sequencing, reads are polyadenylated and enter the nanopore at the 3' end, so NanoCount filters out alignments that are far from the 3' ends. However, if you're using it in the cDNA mode this doesn't apply.

You can restrict read filtering further using various minimap2 or NanoCount filters, feel free to let me know a more specific example and I can try and help.

Thanks

**Comment by kerenzhou062** [comment]
Thank you so much for the information! So another question is that, how can I evaluate the expression level on gene level instead of isoform level? Can I sum up all the reads counts from transcripts of a gene and take it as the expression level of this gene? 

Thanks!
Keren

**Comment by josiegleeson** [comment]
Yes exactly, you can sum the total counts for all isoforms expressed per gene. Or you can re-map your reads to the genome with minimap2 and then use something like featureCounts to quantify gene expression. But both ways are common.

Thanks :)

**Comment by kerenzhou062** [comment]
Hi Josie, 

I'm wondering that whether I can obtain the reads counts for gene by directly mapping reads to sequence from the whole gene locus instead of transcripts (minimap2 -ax splice)?  Here is the example for the fasta file:
>ENSG00000240409.1
ATGCCCCAACTAAATACTACCGTATGACCCACCATAATTACCCCCATACTCCTTACACTATTCCTCATCACCCAACTAAAAATATTAAATACAAATTACCACCTACCTCCCTCACCAAAGCCCATAAAAATAAAAAACTATAACAAACCCTGAGAACCAAAATGAACGAAAATCTGTTCACTTCATTCATTGCCCCCACAATCCTAG
>ENSG00000248527.1
ATGAACGAAAATCTGTTCACTTCATTCATTGCCCCCACAATCCTAGGCCTACCCGCCGCAGTACTGATCATTCTATTTCCCCCTCTATTGATCCCCACCTCCAAATATCTCATCAACAACCGACTAATTACCACCCAACAATGACTAATCCAACTAACCTCAAAACAAATGATAGCCATACACAACACTAAGGGACGAACCTGATCTCTTATACTAGTATCCTTAATCATTTTTATTGCCACAACTAACCTCCTCGGACTCCTGCCTCACTCATTTACACCAACCACCCAACTATCTATAAACCTAGCCATGGCCATCCCCTTATGAGCGGGCGCAGTGATTATAGGCTTTCGCTCTAAGATTAAAAATGCCCTAGCCCACTTCTTACCACAAGGCACACCTACACCCCTTATCCCTATACTAGTTATTATCGAAACCATCAGCCTACTCATTCAACCAATAGCCCTGGCCGTACGCCTAACCGCTAACATTACTGCAGGCCACCTACTCATGCACCTAATTGGAAGCGCCACACTAGCAATATCAACTATTAACCTTCCCTCTACACTTATCATCTTCACAATTCTAATTCTACTGACTATCCTAGAAATCGCTGTCGCCTTAATCCAAGCCTACGTTTTTACACTTCTAGTAAGCCTCTACCTGCACGACAACACATAA
>ENSG00000198744.5
ATGACCCACCAATCACATGCCTATCATATAGTAAAACCCAGCCCATGGCCCCTAACAGGGGCCCTCTCAGCCCTCCTAATGACCTCCGGCCTAGCCATGTGATTTCACTTCCACTCCACAACCCTCCTCATACTAGGCCTACTAACCAACACACTAACCATATACCAATGATGGCGCGATGTAACACGAGAAAGCACATACCAAGGCCACCACACACCACCTGTCCAGAAAGGCCTTCGATACGGGATAATCCTATTTATTACCTCAGAAGTTTTTTTCTTCGCAGGATTTTTCTGAGCCTTTTACCACTCCAGCCTAGCTCCCACCCCCCAACTAGGGGGACACTGGCCCCCAACAGGCATCACCCCGCTAAATCCCCTAGAAGTCCCACTCCTAAACACATCCGTATTACTCGCATCAGGGGTATCAATCACCTGAGCTCACCATAGTCTAATAGAAAACAACCGAAACCAAATAATTCAAGCACTGCTTATTACAATTTTACTGGGTCTCTATTTTACCCTCCTACAAGCCTCAGAGTACTTCG

Thanks!
Keren
