### ISSUE TITLE
Question about normalisation

### ISSUE THREAD

**Issue by tleonardi** [a-slide/NanoCount#4]
I don't understand why at the line below the estimated counts are multiplied by the total number of reads instead of being divided.. might be related to #3?

https://github.com/a-slide/NanoCount/blob/d79d5a95be99c01ed9fbead38303200737b6d39b/NanoCount/NanoCount.py#L112

**Comment by tleonardi** [comment]
Having a better look at this, it seems "raw" is already normalised by the total number of reads (the sum of the 'raw' column is 1): therefore multiplying by len(self.read_dict) should give you back the (estimated) number of reads. Correct?

**Comment by a-slide** [comment]
So I guess we are good then.
