### ISSUE TITLE
Release version 1.1.0 on pypi and fix version string in 1.1.0 release

### ISSUE THREAD

**Issue by rob-p** [a-slide/NanoCount#40]
Hi,

  Thanks for the nice tool!  I just wanted to point out that in the latest github release, the version string reads 1.0.0post6, though the release is tagged as 1.1.0 (and the latest on the `main` branch is 1.1.0).  Presumably, these should be consistent.

  Also, it would be very helpful for installation purposes if you could push v1.1.0 to pypi to ease installation.

Thanks!

**Comment by josiegleeson** [comment]
Hi Rob,

Thanks for noticing this! I'll try and fix it now.
